#This is not exactly a pvc but a storage class definition for ebs. You can create a pv and pvc for hostPath if you wanna use node specific storage but that is also ephemeral like pods. For production use cases you should use ebs or other cloud provider storage classes.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-api-test-ebs
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer 

# If you wanna use node specific storage i.e. hostPath in pv.yml specifies that on an node data is stored. But ofc node is also ephemeral like pods
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: fast-api-test-pv
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 16Gi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: /mnt/data/fast-api-test