apiVersion: v1
kind: PersistentVolume
metadata:
  name: fast-api-test-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/fast-api-test