apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fast-api-test-pvc
  namespace: default
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 16Gi
  accessModes:
    - ReadWriteMany
