apiVersion: v1
kind: Service
metadata:
  name: fast-api-test-service
  namespace: default
  labels:
    app: fast-api-test
    env: development
spec:
  type: NodePort
  selector:
    app: fast-api-test
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
